### ISSUE TITLE
separate arpeggio and scale

### ISSUE THREAD

**Issue by sugizo** [cheap-glitch/fretboarder#22]
### Description

there's a lot of scale and arpeggio in music, better to separate it using html select tag 

### Implementation details

add another html select tag to choose 'arpeggio or scale', then when it's select scale, it will load all scales defined, vice versa 

### Examples

https://scribbletune.github.io/johann/#/guitar

**Comment by cheap-glitch** [comment]
> add another html select tag to choose 'arpeggio or scale', then when it's select scale, it will load all scales defined, vice versa

This was the case in a previous design, but it added needless clutter and took space away from more important stuff on smaller screens.

It's true that the list is long, but that's why I duplicated the "common" scales and arpeggios at the top. Plus on desktop you can jump to an item by typing the first few letters of its label when the select menu is opened.
